import { router } from 'expo-router';
import { useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import type { ImportItem } from '@/domain/types';
import type { ImportSummary } from '@/domain/import';
import { commitImport, correctImportItem, importCandidates } from '@/domain/import';
import { importPhoto, initialImportItems } from '@/fixtures/imports';
import { placeById, places } from '@/fixtures/catalog';
import { useApp } from '@/state/AppProvider';
import { Button, Chip, ChipRow, DemoLabel, EmptyState, Field, Header, Icon, Screen, Sheet, T } from '@/components/ui';
import { PlacePhoto } from '@/components/cards/PlacePhoto';
import { colors } from '@/design/tokens';
type Stage = 'intro' | 'scan' | 'review' | 'summary';
export default function DropboxImport() {
  const { state, commit } = useApp(); const [stage, setStage] = useState<Stage>(state.importItems.length ? 'review' : 'intro'); const [scanCount, setScanCount] = useState(0); const [summary, setSummary] = useState<ImportSummary>();
  const [editing, setEditing] = useState<string>(); const [date, setDate] = useState(''); const [placeId, setPlaceId] = useState(''); const [editorError, setEditorError] = useState('');
  const items = state.importItems; const selected = importCandidates(state, items).length;
  const groupKey = (item: ImportItem) => item.status === 'eligible' ? item.placeId : item.status;
  const reviewGroups = [...new Set(items.map(groupKey))].map(key => ({ key, items: items.filter(item => groupKey(item) === key), title: placeById(key)?.name ?? (key === 'duplicate' ? 'Duplicate photos excluded' : key === 'unresolved' ? 'Needs your review' : 'Unsupported photos') }));
  const persist = (next: ImportItem[]) => commit({ type: 'IMPORT_ITEMS', items: next });
  const openEditor = (item: ImportItem) => { const photo = importPhoto(item.id); setEditing(item.id); setDate(item.visitedAt.slice(0, 10)); setPlaceId(item.placeId || photo?.previewPlaceId || ''); setEditorError(''); };
  const closeEditor = () => { setEditing(undefined); setEditorError(''); };
  const saveCorrection = async () => { const item = items.find(candidate => candidate.id === editing); if (!item) return; try { const corrected = correctImportItem(item, placeId, date, state.clock); await persist(items.map(candidate => candidate.id === item.id ? corrected : candidate)); closeEditor(); } catch (error) { setEditorError(error instanceof Error ? error.message : 'Could not update this photo.'); } };
  const start = () => { setScanCount(0); setStage('scan'); };
  const advance = async () => { const next = Math.min(12, scanCount + 4); setScanCount(next); if (next === 12) { await commit({ type: 'IMPORT_ITEMS', items: initialImportItems() }); setStage('review'); } };
  const finish = async () => { const before = state; const result = await commitImport(before, items, commit); setSummary(result.summary); setStage('summary'); };
  if (state.mode === 'account') return <Screen><Header back title="Photo import" /><T>Dropbox import uses bundled demo photos and is available only in local demo mode. It cannot add sample visits to your account.</T><Button label="Capture a real photo" onPress={() => router.replace('/capture')} /></Screen>;
  if (stage === 'summary' && summary) return <Screen><Header back title="Import complete" /><View style={styles.success}><Icon name="check" size={42} /><T variant="title">Memories reviewed</T><T muted style={{ textAlign: 'center' }}>The summary below comes from actual saved editions, not the scan estimate.</T></View><SummaryRow label="Editions created" value={summary.createdEditions} /><SummaryRow label="Distinct new places" value={summary.newPlaces} /><SummaryRow label="Duplicates skipped" value={summary.duplicatesSkipped} /><SummaryRow label="Unresolved left out" value={summary.unresolved} /><SummaryRow label="Unsupported left out" value={summary.unsupported} />{summary.deselected > 0 && <SummaryRow label="Eligible photos left out" value={summary.deselected} />}<Button label="Open collection" onPress={() => router.replace('/collection')} /><Button label="Review this library again" variant="ghost" onPress={() => setStage('review')} /></Screen>;
  if (stage === 'scan') return <Screen><Header title="Scanning demo library" /><View style={styles.scan}><Icon name="upload" size={44} /><T variant="title">{scanCount} of 12 photos</T><View style={styles.progress}><View style={[styles.progressFill, { width: `${scanCount / 12 * 100}%` }]} /></View><DemoLabel label="Fixed local fixture · no Dropbox account" /><T muted style={{ textAlign: 'center' }}>Photos are grouped by proposed visit. Nothing is saved to your collection during scanning.</T></View><Button label={scanCount === 8 ? 'Finish scan' : 'Scan next 4 photos'} onPress={advance} /><Button label="Cancel scan" variant="ghost" onPress={() => setStage(state.importItems.length ? 'review' : 'intro')} /></Screen>;
  if (stage === 'intro') return <Screen><Header back title="Import from Dropbox" /><PlacePhoto placeId="la-the-broad" style={{ height: 210 }} /><View style={{ gap: 12, paddingVertical: 22 }}><DemoLabel label="Dropbox simulation" /><T variant="heading">Preview an import using sample photos</T><T muted>No login, OAuth screen, or external connection is used. You’ll review a fixed 12-photo library before anything joins your collection.</T><T>Expected scan: 8 eligible visits in 6 destination groups, 2 duplicates, 1 photo needing a place, and 1 unsupported file.</T></View>{state.preferences.sourceStatus === 'unavailable' ? <EmptyState icon="cloud" title="Demo source unavailable" message="The source-unavailable scenario is active. Restore sample sources to try this local import." action="Restore sample source" onPress={() => commit({ type: 'PREFERENCES', patch: { sourceStatus: 'sample' } })} /> : <Button label="Use demo Dropbox library" icon="upload" onPress={start} />}</Screen>;
  return <Screen><Header back title="Review import" subtitle={`${selected} eligible visits selected`} /><DemoLabel label="Demo confidence · review required" /><T muted style={{ marginBottom: 14 }}>Corrections and selections are persisted as a review draft. Import is idempotent: previously imported photo hashes are skipped.</T>
    <View>{reviewGroups.map(group => <View key={group.key}><T variant="heading" style={{ marginTop: 20 }}>{group.title}</T><T variant="small" muted>{group.items.length} {group.items.length === 1 ? 'photo' : 'photos'} · different dates remain separate visits</T>{group.items.map(item => { const photo = importPhoto(item.id)!; const place = placeById(item.placeId || photo.previewPlaceId); const imported = state.importedSourceIds.includes(`dropbox-demo:${photo.contentHash}`); const selectable = item.status === 'eligible' && !imported; return <View key={item.id} style={styles.item}><PlacePhoto placeId={photo.previewPlaceId || 'unknown'} style={{ width: 72, height: 78 }} /><Pressable accessibilityRole="button" disabled={imported || item.status === 'unsupported' || item.status === 'duplicate'} onPress={() => openEditor(item)} style={{ flex: 1, gap: 2 }}><T variant="label">{place?.name ?? (item.status === 'unsupported' ? 'Unsupported file' : 'Choose a place')}</T><T variant="small" muted>{photo.fileName} · Source: {photo.visitedAt.slice(0, 10)}{item.visitedAt !== photo.visitedAt ? ` · Corrected: ${item.visitedAt.slice(0, 10)}` : ''}</T><T variant="small" color={item.status === 'eligible' ? colors.brand : item.status === 'duplicate' ? colors.muted : colors.error}>{imported ? 'Already imported · will skip' : item.status === 'eligible' ? `${photo.confidence === 'low' ? 'Low' : 'High'} demo confidence · Edit` : item.status === 'duplicate' ? 'Duplicate photo excluded' : item.status === 'unsupported' ? 'RAW format unsupported' : 'Needs manual place selection'}</T></Pressable><Pressable accessibilityRole="checkbox" accessibilityLabel={`Select ${photo.fileName}`} accessibilityState={{ checked: selectable && item.selected, disabled: !selectable }} disabled={!selectable} onPress={() => { void persist(items.map(candidate => candidate.id === item.id ? { ...candidate, selected: !candidate.selected } : candidate)).catch(() => undefined); }} style={[styles.check, item.selected && selectable && styles.checked, !selectable && { opacity: .35 }]}>{item.selected && selectable && <Icon name="check" size={17} color="#fff" />}</Pressable></View>; })}</View>)}</View>
    <Button label={`Import ${selected} selected ${selected === 1 ? 'visit' : 'visits'}`} disabled={selected === 0} onPress={finish} style={{ marginTop: 24 }} /><Button label="Cancel and keep review draft" variant="ghost" onPress={() => router.canGoBack() ? router.back() : router.replace('/profile')} />
    <Sheet visible={!!editing} onClose={closeEditor} title="Correct photo">{editing && <PlacePhoto placeId={importPhoto(editing)?.previewPlaceId || 'unknown'} style={{ height: 170 }} />}<Field label="Visit date" value={date} onChangeText={setDate} placeholder="YYYY-MM-DD" /><T variant="label">Destination</T><ChipRow>{places.map(place => <Chip key={place.id} label={place.name} selected={placeId === place.id} onPress={() => setPlaceId(place.id)} />)}</ChipRow>{Boolean(editorError) && <T color={colors.error}>{editorError}</T>}<Button label="Save correction" onPress={saveCorrection} /><Button label="Cancel" variant="ghost" onPress={closeEditor} /></Sheet>
  </Screen>;
}
function SummaryRow({ label, value }: { label: string; value: number }) { return <View style={styles.summary}><T>{label}</T><T variant="heading" color={colors.brand}>{value}</T></View>; }
const styles = StyleSheet.create({ scan: { flex: 1, minHeight: 390, justifyContent: 'center', alignItems: 'center', gap: 18 }, progress: { height: 8, width: '100%', backgroundColor: colors.divider, borderRadius: 4, overflow: 'hidden' }, progressFill: { height: '100%', backgroundColor: colors.brand }, item: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 12, borderBottomWidth: 1, borderBottomColor: colors.divider }, check: { height: 44, width: 44, borderRadius: 8, borderWidth: 1, borderColor: colors.brand, alignItems: 'center', justifyContent: 'center' }, checked: { backgroundColor: colors.brand }, success: { alignItems: 'center', paddingVertical: 25, gap: 10 }, summary: { minHeight: 55, borderBottomWidth: 1, borderBottomColor: colors.divider, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' } });
