export const mobileFixtureToSlug = {
  "la-griffith-park": "griffith-park",
  "la-echo-park": "echo-park-lake",
  "la-elysian-park": "elysian-park",
  "la-grand-park": "grand-park",
  "la-state-historic-park": "los-angeles-state-historic-park",
  "la-barnsdall": "barnsdall-art-park",
  "la-macarthur": "macarthur-park",
  "la-rose-garden": "exposition-park-rose-garden",
  "la-lake-balboa": "lake-balboa-park",
  "la-vista-hermosa": "vista-hermosa-natural-park",
  "la-the-broad": "the-broad",
  "la-moca": "moca-grand-avenue",
  "la-janm": "japanese-american-national-museum",
  "la-central-library": "los-angeles-central-library",
  "la-caam": "california-african-american-museum",
  "la-science-center": "california-science-center",
  "la-griffith-observatory": "griffith-observatory",
  "la-autry": "autry-museum",
  "la-lacma": "los-angeles-county-museum-of-art",
  "la-getty": "the-getty-center",
  "la-disney-hall": "walt-disney-concert-hall",
  "la-bradbury": "bradbury-building",
  "la-angels-flight": "angels-flight",
  "la-union-station": "union-station",
  "la-olvera": "olvera-street",
  "la-watts-towers": "watts-towers",
  "la-hollywood-walk": "hollywood-walk-of-fame",
  "la-venice-canals": "venice-canals",
  "la-hollywood-bowl": "hollywood-bowl",
  "la-korean-bell": "korean-bell-of-friendship",
} as const;

export const mobileCategoryToCanonical = {
  park: "nature",
  cultural: "culture",
  landmark: "landmark",
} as const;
