import { router, useLocalSearchParams } from 'expo-router';
import { useMemo, useState } from 'react';
import { Pressable, StyleSheet, View } from 'react-native';
import type { Sentiment } from '@/domain/types';
import { beginRanking, compare, comparisonTarget, finishRanking, undoComparison, type RankingSession } from '@/domain/rankings';
import { placeById, categoryLabels } from '@/fixtures/catalog';
import { useApp } from '@/state/AppProvider';
import { ownEditions } from '@/state/selectors';
import { Button, DemoLabel, EmptyState, Header, Icon, Screen, T } from '@/components/ui';
import { PlacePhoto } from '@/components/cards/PlacePhoto';
import { colors } from '@/design/tokens';
const sentimentChoices: { value: Sentiment; label: string; detail: string; color: string }[] = [
  { value: 'recommend', label: 'Yes', detail: 'Would recommend', color: colors.positive }, { value: 'depends', label: 'It depends', detail: 'Right for some visits', color: colors.neutral }, { value: 'skip', label: 'Would skip', detail: 'Not one I’d suggest', color: colors.negative },
];
export default function RecommendScreen() {
  const { placeId, editionId } = useLocalSearchParams<{ placeId?: string; editionId?: string }>(); const { state, commit } = useApp(); const place = placeId ? placeById(placeId) : undefined;
  const visit = ownEditions(state).find(edition => edition.placeId === placeId && (!editionId || edition.id === editionId)); const existing = state.assessments.find(item => item.placeId === placeId);
  const [sentiment, setSentiment] = useState<Sentiment | undefined>(existing?.sentiment); const [session, setSession] = useState<RankingSession>(); const [saved, setSaved] = useState(false);
  const targetId = session ? comparisonTarget(session) : undefined; const target = targetId ? placeById(targetId) : undefined;
  const finished = !!session && !targetId; const result = useMemo(() => session && sentiment ? finishRanking(session, sentiment, visit?.id) : undefined, [session, sentiment, visit?.id]);
  if (!place || !visit) return <Screen><Header back title="Recommendation unavailable" /><EmptyState title={!place ? 'Place not found' : 'Visit required'} message={!place ? 'This destination is not available in the demo.' : 'Recommendations are personal to places you have collected.'} action="Back to collection" onPress={() => router.replace('/collection')} /></Screen>;
  const start = (finish = false) => { if (!sentiment) return; setSaved(false); setSession(beginRanking(place.id, place.category, sentiment, state.rankings, finish)); };
  const save = async () => { if (!result) return; await commit({ type: 'ASSESS', assessment: result.assessment, ranking: result.ranking }); setSaved(true); };
  if (saved && result) return <Screen><Header back title="Recommendation saved" /><View style={styles.saved}><Icon name="check" size={38} /><T variant="heading">{result.assessment.ranking === 'settled' ? 'Your ranking is set' : result.assessment.ranking === 'provisional' ? 'Provisional rank saved' : 'Sentiment saved'}</T><T muted style={{ textAlign: 'center' }}>{result.assessment.ranking === 'unranked' ? 'You skipped comparison. No score or rank was invented.' : result.assessment.ranking === 'provisional' ? 'Two quick comparisons narrowed the range. You can finish it now or later.' : 'This updates your personal category order.'}</T></View>{result.assessment.ranking === 'provisional' && <Button label="Finish ranking" onPress={() => start(true)} />}<Button label="Back to collection" variant="outline" onPress={() => router.replace('/collection')} /></Screen>;
  return <Screen><Header back title={place.name} subtitle="Your private recommendation" /><PlacePhoto placeId={place.id} uri={visit.photoUri} style={{ height: 190 }} /><DemoLabel label="Personal assessment" />
    {!session ? <View style={{ gap: 22, paddingTop: 20 }}><View style={{ gap: 5 }}><T variant="heading">Would you recommend this place?</T><T muted>This becomes your current recommendation. It does not create a public score.</T></View><View style={styles.sentiments}>{sentimentChoices.map(choice => <Pressable key={choice.value} accessibilityRole="radio" accessibilityState={{ checked: sentiment === choice.value }} onPress={() => setSentiment(choice.value)} style={[styles.sentiment, { backgroundColor: choice.color }, sentiment === choice.value && styles.selected]}><Icon name={choice.value === 'recommend' ? 'heart' : choice.value === 'depends' ? 'info' : 'close'} size={25} /><T variant="label" style={{ textAlign: 'center' }}>{choice.label}</T><T variant="small" style={{ textAlign: 'center' }}>{choice.detail}</T></Pressable>)}</View><T variant="label">Compare within: {categoryLabels[place.category]}</T><Button disabled={!sentiment} label="Compare places" onPress={() => start(false)} /><Button label="Save without ranking" variant="ghost" disabled={!sentiment} onPress={() => { if (!sentiment) return; setSession(compare(beginRanking(place.id, place.category, sentiment, state.rankings), 'skip')); }} /></View> : !finished && target ? <View style={{ gap: 19, paddingTop: 20 }}><View><T variant="heading">Which would you recommend?</T><T muted>{session.comparisons + 1} of at most {Number.isFinite(session.limit) ? session.limit : 'all'} comparisons · {categoryLabels[place.category]}</T></View><View style={styles.compare}><PlaceChoice name={place.name} placeId={place.id} onPress={() => setSession(compare(session, 'prefer-new'))} /><View style={styles.or}><T variant="label">or</T></View><PlaceChoice name={target.name} placeId={target.id} onPress={() => setSession(compare(session, 'prefer-existing'))} /></View><View style={styles.tools}><Button label="Undo" variant="ghost" disabled={session.history.length === 0} onPress={() => setSession(undoComparison(session))} /><Button label="Too close" variant="ghost" onPress={() => setSession(compare(session, 'tie'))} /><Button label="Skip" variant="ghost" onPress={() => setSession(compare(session, 'skip'))} /></View></View> : <View style={{ gap: 16, paddingTop: 24 }}><T variant="heading">Ready to save</T><T>{result?.assessment.ranking === 'provisional' ? 'Provisional rank' : result?.assessment.ranking === 'settled' ? result.assessment.tiedWith ? 'Tied rank' : 'Settled category rank' : 'Unranked sentiment'}</T><T muted>Changes are not persisted until you save.</T><Button label="Save recommendation" onPress={save} /><Button label="Undo last comparison" variant="ghost" disabled={session.history.length === 0} onPress={() => setSession(undoComparison(session))} /></View>}
  </Screen>;
}
function PlaceChoice({ name, placeId, onPress }: { name: string; placeId: string; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityLabel={`Choose ${name}`} onPress={onPress} style={styles.choice}><PlacePhoto placeId={placeId} style={{ height: 120 }} /><T variant="place" style={{ textAlign: 'center' }}>{name}</T></Pressable>; }
const styles = StyleSheet.create({ sentiments: { flexDirection: 'row', gap: 10 }, sentiment: { flex: 1, aspectRatio: .82, borderRadius: 80, alignItems: 'center', justifyContent: 'center', padding: 8, gap: 5, borderWidth: 2, borderColor: 'transparent' }, selected: { borderColor: colors.brand }, compare: { flexDirection: 'row', alignItems: 'center' }, choice: { flex: 1, gap: 10, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 10 }, or: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', marginHorizontal: -4, zIndex: 2 }, tools: { flexDirection: 'row', justifyContent: 'center', flexWrap: 'wrap' }, saved: { paddingVertical: 35, alignItems: 'center', gap: 12 } });
